env_vars:
 - name: needs_reparse
input_vars:
 - name: needs_reparse
seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - page_type: init
    file: ./parsers/init.rb
    disabled: false
  - page_type: categories
    file: ./parsers/categories.rb
    disabled: false
  # - page_type: subcategories
  #   file: ./parsers/subcategories.rb
  #   disabled: false
  # - page_type: listings
  #   file: ./parsers/listings.rb
  #   disabled: false
  # - page_type: product_api
  #   file: ./parsers/product_api.rb
  #   disabled: false

# finisher:
#   file: ./finisher/finisher.rb
#   disabled: true

# exporters:
#   - file: ./exporters/products_json.yaml
#     disabled: false
#   - file: ./exporters/products_csv.yaml
#     disabled: false